QA на GitHub Actions
EvilBeaver/OneScript.Web pull request #78
Opened 2020-10-30 18:41 UTC by otymko

* Отправка на sonarcloud.io
* Покрытия нет
* Количество тестов нет

2020-10-30 18:42 UTC, otymko commented
@EvilBeaver Нужно зафиксировать 2 секрета:
* `SONAR_TOKEN`
* `SONAR_HOST`

2020-11-05 01:49 UTC, sfaqer requested changes

2020-11-05 01:49 UTC, sfaqer commented on .github/workflows/qa.yml
> +    - run: dotnet sonarscanner begin /k:"otymko_OneScript.Web" /o:"otymko" /d:sonar.login=${{ env.SONAR_TOKEN }} /d:sonar.host.url=${{ env.SONAR_HOST }}
@otymko 
otnet sonarscanner begin /k:**"otymko_OneScript.Web"** **/o:"otymko"**
Прям в твою учётку прихардкожено весь скан должен сыпатся?

2020-11-05 02:13 UTC, otymko commented on .github/workflows/qa.yml
> +    - run: dotnet sonarscanner begin /k:"otymko_OneScript.Web" /o:"otymko" /d:sonar.login=${{ env.SONAR_TOKEN }} /d:sonar.host.url=${{ env.SONAR_HOST }}
Ага, косяк. Надо ждать пока Андрей проект создаст на клауде

2020-11-06 10:57 UTC, EvilBeaver commented on .github/workflows/qa.yml
> +    - run: dotnet sonarscanner begin /k:"otymko_OneScript.Web" /o:"otymko" /d:sonar.login=${{ env.SONAR_TOKEN }} /d:sonar.host.url=${{ env.SONAR_HOST }}
А на openbsl - нереально сделать? Обязательно в клауд?

2020-11-06 13:11 UTC, otymko commented on .github/workflows/qa.yml
> +    - run: dotnet sonarscanner begin /k:"otymko_OneScript.Web" /o:"otymko" /d:sonar.login=${{ env.SONAR_TOKEN }} /d:sonar.host.url=${{ env.SONAR_HOST }}
@EvilBeaver пока @nixel2007 дев версию плагина не поставит..

2020-11-06 14:11 UTC, nixel2007 commented on .github/workflows/qa.yml
> +    - run: dotnet sonarscanner begin /k:"otymko_OneScript.Web" /o:"otymko" /d:sonar.login=${{ env.SONAR_TOKEN }} /d:sonar.host.url=${{ env.SONAR_HOST }}
Я не против, я просто думал, что вы на сонарклауд договорились.

2020-11-07 11:07 UTC, EvilBeaver commented on .github/workflows/qa.yml
> +    - run: dotnet sonarscanner begin /k:"otymko_OneScript.Web" /o:"otymko" /d:sonar.login=${{ env.SONAR_TOKEN }} /d:sonar.host.url=${{ env.SONAR_HOST }}
Ну openbsl-то пизже. А я подожду пока плагин станет не-дев

2020-11-07 11:50 UTC, nixel2007 commented on .github/workflows/qa.yml
> +    - run: dotnet sonarscanner begin /k:"otymko_OneScript.Web" /o:"otymko" /d:sonar.login=${{ env.SONAR_TOKEN }} /d:sonar.host.url=${{ env.SONAR_HOST }}
А я накатил уже :)

2020-11-23 10:03 UTC, EvilBeaver commented
Gents, а что тут делаем? Вмерживаем или еще что-то нужно сделать?

2020-11-23 10:09 UTC, otymko commented
@EvilBeaver Нужно поправить workflow и секреты под https://sonar.openbsl.ru . Думаю мне нужно пару дней, чтобы добраться до PR

2020-12-14 17:23 UTC, merged